vectorstore:
  clear_store: false
  collection_name: 'chunk_1000_200_ada_002'
  use_existing_vectorstore: true
chunking:
  chunk_type: recursive_character_splitter
  chunk_size: 1000
  chunk_overlap: 200
retrieval:
  k_documents: 5
  use_ensemble: true
  use_multiquery: false
  use_reranker: false
  use_cohere_reranker: false
  top_n_ranked: 5
models:
  generator_model: 'gpt-4o'
  queries_generator_model: 'gpt-3.5-turbo'
